---
deployment:
  tasks:
    - /bin/cp -f index.html sobre.html contato.html costao.html fazzenda.html japaratinga.html admin.html content-override.js /home/rsxtrave/public_html/
    - /bin/cp -rf design_handoff_rsx_travel_site /home/rsxtrave/public_html/
